import { supabase } from '@/lib/supabase';
import type { PurchaseOrder } from '../types';
import {
  buildCofHtml,
  openCofHtmlInNewTab,
  type CofFieldOverrides,
} from './generateCofPdf';

type RequestorInfo = Parameters<typeof buildCofHtml>[1];

async function fetchRequestorInfo(poId: string): Promise<RequestorInfo> {
  try {
    const { data, error } = await supabase.rpc('get_po_requestor_info', { p_po_id: poId });
    if (error) {
      console.warn('[Warehouse COF] get_po_requestor_info error:', error);
      return { company: null, profile: null };
    }
    const obj = (data || {}) as Partial<RequestorInfo>;
    return {
      company: obj.company ?? null,
      profile: obj.profile ?? null,
    };
  } catch (e) {
    console.warn('[Warehouse COF] get_po_requestor_info exception:', e);
    return { company: null, profile: null };
  }
}

const WAREHOUSE_SIGNOFF_CSS = `
  .wh-signoff {
    width: 100%;
    border-collapse: collapse;
    table-layout: fixed;
    margin-top: 10px;
    font-size: 9px;
  }
  .wh-signoff th,
  .wh-signoff td {
    border: 1px solid #000;
    padding: 4px 6px;
    text-align: left;
    vertical-align: top;
    font-weight: 700;
  }
  .wh-signoff .sig-space {
    height: 52px;
    font-weight: 600;
    line-height: 1.7;
  }
  .wh-signoff .role-row td { font-weight: 700; }
  .wh-signoff .date-row td { font-weight: 600; }
`;

const WAREHOUSE_SIGNOFF_HTML = `
    <table class="wh-signoff">
      <thead>
        <tr>
          <th>Prepared by</th>
          <th>Checked by</th>
          <th>Verified by</th>
          <th>Courier / Customer</th>
        </tr>
      </thead>
      <tbody>
        <tr class="sig-space">
          <td></td>
          <td></td>
          <td></td>
          <td>
            <div>Name:</div>
            <div>Plate No:</div>
            <div>Contact No:</div>
          </td>
        </tr>
        <tr class="role-row">
          <td>Warehouse staff</td>
          <td>Warehouse supervisor</td>
          <td>Warehouse Manager</td>
          <td></td>
        </tr>
        <tr class="date-row">
          <td>Date:</td>
          <td>Date:</td>
          <td>Date:</td>
          <td>Date:</td>
        </tr>
      </tbody>
    </table>
`;

function attachWarehouseSignoff(html: string): string {
  const withCss = html.replace('</style>', `${WAREHOUSE_SIGNOFF_CSS}\n</style>`);
  return withCss.replace(
    '<div class="footer-note">Generated by B1G Ordering System</div>',
    `${WAREHOUSE_SIGNOFF_HTML}\n    <div class="footer-note">Generated by B1G Ordering System</div>`
  );
}

/**
 * Warehouse Customer Order Form — same COF layout as generateCofPdf,
 * plus the warehouse prepared/checked/verified/courier sign-off table.
 */
export async function generateAndOpenWarehouseCofPdf(
  po: PurchaseOrder,
  overrides?: CofFieldOverrides
) {
  const requestor = await fetchRequestorInfo(po.id);
  const html = attachWarehouseSignoff(buildCofHtml(po, requestor, overrides));
  openCofHtmlInNewTab(html);
}
