-- Fix remittance signatures storage access for signed URLs
-- This configuration keeps the bucket PRIVATE and uses signed URLs for access
-- Access control is handled by the get_remittance_signature_url() function

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Allow authenticated users to read remittance signatures" ON storage.objects;
DROP POLICY IF EXISTS "Public read access for remittance signatures" ON storage.objects;

-- Create policy to allow authenticated users to read their authorized remittance signatures
-- This works with signed URLs generated by the get_remittance_signature_url() function
CREATE POLICY "Authenticated users can read remittance signatures via signed URLs"
ON storage.objects FOR SELECT
TO authenticated
USING (
    bucket_id = 'remittance-signatures' 
    AND auth.role() = 'authenticated'
);

-- Policy for inserting signatures (for mobile sales and team leaders when creating remittances)
CREATE POLICY "Authenticated users can upload remittance signatures"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (
    bucket_id = 'remittance-signatures'
    AND auth.role() = 'authenticated'
);

-- Policy for updating signatures (if needed)
CREATE POLICY "Users can update their own remittance signatures"
ON storage.objects FOR UPDATE
TO authenticated
USING (
    bucket_id = 'remittance-signatures'
    AND auth.role() = 'authenticated'
);

-- Policy for deleting signatures (restricted to admins)
CREATE POLICY "Only admins can delete remittance signatures"
ON storage.objects FOR DELETE
TO authenticated
USING (
    bucket_id = 'remittance-signatures'
    AND EXISTS (
        SELECT 1 FROM profiles
        WHERE profiles.id = auth.uid()
        AND profiles.role IN ('super_admin', 'admin', 'system_administrator')
    )
);

-- Ensure the bucket exists and is PRIVATE
DO $$
BEGIN
    -- Check if bucket exists
    IF NOT EXISTS (SELECT 1 FROM storage.buckets WHERE id = 'remittance-signatures') THEN
        RAISE NOTICE 'Creating remittance-signatures bucket...';
        INSERT INTO storage.buckets (id, name, public)
        VALUES ('remittance-signatures', 'remittance-signatures', false);
    ELSE
        -- Ensure bucket is set to PRIVATE (not public)
        UPDATE storage.buckets
        SET public = false
        WHERE id = 'remittance-signatures';
        RAISE NOTICE 'remittance-signatures bucket is now PRIVATE (signed URLs will be used)';
    END IF;
END $$;

-- Add helpful comment
COMMENT ON POLICY "Authenticated users can read remittance signatures via signed URLs" ON storage.objects IS 
'Allows authenticated users to access signatures through signed URLs. Authorization is enforced by get_remittance_signature_url() function.';
